# Generated by Django 3.1.4 on 2022-05-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.IntegerField()),
                ('count', models.IntegerField()),
                ('seller_or_tailor_price', models.IntegerField()),
            ],
        ),
    ]
