# Generated by Django 3.1.4 on 2022-05-11 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counting_app_sellerortailor', '0001_initial'),
        ('counting_app_cloth', '0002_cloth_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='seller_or_tailor_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='counting_app_sellerortailor.sellerortailor'),
            preserve_default=False,
        ),
    ]
