# Generated by Django 3.1.4 on 2022-05-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counting_app_customer', '0002_customer_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='full_name',
            new_name='name',
        ),
    ]
