# Generated by Django 3.1.4 on 2022-05-09 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counting_app_cloth', '0001_initial'),
        ('counting_app_customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('discription', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counting_app_customer.customer')),
                ('pant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counting_app_cloth.cloth')),
            ],
        ),
    ]
