# Generated by Django 3.1.4 on 2022-05-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counting_app_invoice', '0003_invoice_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='discription',
            field=models.TextField(max_length=150),
        ),
    ]
