# Generated by Django 3.1.4 on 2022-05-17 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counting_app_invoice', '0005_auto_20220517_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='pant',
            new_name='cloth',
        ),
    ]
