# Generated by Django 3.1.4 on 2022-05-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counting_app_invoice', '0007_auto_20220518_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetails',
            name='code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
