# Generated by Django 3.1.4 on 2022-05-18 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counting_app_invoice', '0008_invoicedetails_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='discription',
            new_name='description',
        ),
    ]
